### PR TITLE
[ezpz] Change app name from Ring-A-Senior to 'Call-Home'

### PR DESCRIPTION
**Pull request by dchiaseeds**
Test Plan:
Tested using `npm start`, and app name changed

### CODE REVIEW

**Comment by dchiaseeds** [comment]
No conflict! @glencbz  :D

**Comment by dchiaseeds** [comment]
macro_ezpz

**Comment by glencbz** [comment]
Looks great!

**Comment by dchiaseeds** [comment]
lgtm

**Pull request merged**
